[NCL-7410] Update Node.js (18.12.x) and NPM (8.19.x) environments
project-ncl/pnc-web-ui-react-e2e-tests pull request #8
Opened 2022-11-10 12:30 UTC by patrikk0123

2022-11-21 04:36 UTC, DnsZhou requested changes
Hi Patrik, 

Thanks for the work. The new version of node actually works good with cypress, as long as the GUI can be opened. The test error was simply caused by the change to our UI it self, because we haven't update our E2E test for new React since the E2E repo was established.  At the same time I created a jira for updating the cypress for ReactUI which will also fix the test failure: https://issues.redhat.com/browse/NCL-7439 , so no worry for the test failures because that is not a part of building this repo it self.

Also, Do remember to update also the [README.md](https://github.com/project-ncl/pnc-web-ui-react-e2e-tests#readme) in terms of the Prerequisites node/npm version.

Regards,

2022-11-22 08:19 UTC, matedo1 requested changes

2022-11-22 08:19 UTC, matedo1 commented on README.md
> +1. `Node.js` version >= 18
Let's use just link, see for example https://github.com/project-ncl/pnc-web-ui-react/blob/main/README.md#prerequisites

2022-11-22 10:51 UTC, matedo1 approved these changes

2022-12-05 15:00 UTC, matedo1 approved these changes

2022-12-05 15:00 UTC, merged